In [1]:
path = "../raw/gesture.csv"

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(path)

In [4]:
df.head()

,label,x0,y0,z0,x1,y1,z1,x2,y2,z2,...,z17,x18,y18,z18,x19,y19,z19,x20,y20,z20
0,open_palm,0.0,0.0,0.0,-0.267853,-0.166502,-0.146700,-0.490798,-0.432447,-0.228827,...,-0.208417,0.456611,-1.041809,-0.311033,0.558662,-1.225881,-0.365733,0.645383,-1.403194,-0.402040
1,open_palm,0.0,0.0,0.0,-0.265984,-0.174754,-0.137836,-0.482156,-0.443024,-0.216622,...,-0.213260,0.462326,-1.045139,-0.313132,0.566930,-1.229470,-0.366355,0.654401,-1.404609,-0.402018
2,open_palm,0.0,0.0,0.0,-0.266349,-0.171527,-0.145424,-0.485472,-0.438841,-0.229989,...,-0.228315,0.462622,-1.026213,-0.336315,0.572203,-1.204509,-0.392325,0.665830,-1.370468,-0.428388
3,open_palm,0.0,0.0,0.0,-0.260105,-0.173620,-0.144534,-0.479658,-0.446080,-0.229863,...,-0.235701,0.463565,-1.028108,-0.342915,0.573408,-1.212266,-0.397284,0.666025,-1.383456,-0.432468
4,open_palm,0.0,0.0,0.0,-0.258399,-0.186023,-0.131046,-0.480065,-0.471680,-0.207969,...,-0.232332,0.470300,-1.027213,-0.336200,0.582949,-1.208742,-0.390714,0.677675,-1.378430,-0.427127

In [5]:
df.describe()

,x0,y0,z0,x1,y1,z1,x2,y2,z2,x3,...,z17,x18,y18,z18,x19,y19,z19,x20,y20,z20
count,5137.0,5137.0,5137.0,5137.000000,5137.000000,5137.000000,5137.000000,5137.000000,5137.000000,5137.000000,...,5137.000000,5137.000000,5137.000000,5137.000000,5137.000000,5137.000000,5137.000000,5137.000000,5137.000000,5137.000000
mean,0.0,0.0,0.0,-0.190292,-0.141476,-0.123122,-0.350556,-0.335214,-0.227584,-0.403580,...,-0.278986,0.057471,-0.553643,-0.387814,0.028897,-0.434219,-0.373663,0.036314,-0.412038,-0.340668
std,0.0,0.0,0.0,0.175387,0.178795,0.123405,0.315810,0.318266,0.189181,0.414455,...,0.162070,0.492429,0.457098,0.214580,0.493759,0.487570,0.232697,0.497476,0.514962,0.246350
min,0.0,0.0,0.0,-0.566675,-0.683450,-0.559775,-0.934073,-1.211002,-0.918680,-1.282413,...,-0.986813,-1.170825,-1.471041,-1.180376,-1.288972,-1.408682,-1.196315,-1.482519,-1.632261,-1.310135
25%,0.0,0.0,0.0,-0.296422,-0.242146,-0.192483,-0.561480,-0.538945,-0.331530,-0.693636,...,-0.380328,-0.251330,-0.827158,-0.528826,-0.244640,-0.692650,-0.540660,-0.192802,-0.590697,-0.503457
50%,0.0,0.0,0.0,-0.243914,-0.126505,-0.119187,-0.463631,-0.334393,-0.223793,-0.516595,...,-0.266881,0.081737,-0.620191,-0.361697,0.057787,-0.449564,-0.357910,0.069215,-0.410854,-0.327867
75%,0.0,0.0,0.0,-0.165557,-0.031379,-0.054617,-0.271829,-0.125086,-0.120496,-0.173452,...,-0.174304,0.425023,-0.338866,-0.257708,0.354381,-0.199808,-0.221660,0.313246,-0.188640,-0.186998
max,0.0,0.0,0.0,0.472564,0.489961,0.211876,0.797228,0.818332,0.324569,1.026188,...,0.254882,1.192753,1.383919,0.219763,1.367250,1.702451,0.273496,1.563738,1.986612,0.320923

In [6]:
df.info

<bound method DataFrame.info of             label   x0   y0   z0        x1        y1        z1        x2  \
0       open_palm  0.0  0.0  0.0 -0.267853 -0.166502 -0.146700 -0.490798
1       open_palm  0.0  0.0  0.0 -0.265984 -0.174754 -0.137836 -0.482156
2       open_palm  0.0  0.0  0.0 -0.266349 -0.171527 -0.145424 -0.485472
3       open_palm  0.0  0.0  0.0 -0.260105 -0.173620 -0.144534 -0.479658
4       open_palm  0.0  0.0  0.0 -0.258399 -0.186023 -0.131046 -0.480065
...           ...  ...  ...  ...       ...       ...       ...       ...
5132  two_fingers  0.0  0.0  0.0 -0.249736 -0.077076 -0.246265 -0.444192
5133  two_fingers  0.0  0.0  0.0 -0.257324 -0.061177 -0.287692 -0.458585
5134  two_fingers  0.0  0.0  0.0 -0.252948 -0.068788 -0.278077 -0.448187
5135  two_fingers  0.0  0.0  0.0 -0.250222 -0.061195 -0.285570 -0.442760
5136  two_fingers  0.0  0.0  0.0 -0.249370 -0.074634 -0.256276 -0.441845

            y2        z2  ...       z17       x18       y18       z18  \
0    -0.432447 -0.228827  ... -0.208417  0.456611 -1.041809 -0.311033
1    -0.443024 -0.216622  ... -0.213260  0.462326 -1.045139 -0.313132
2    -0.438841 -0.229989  ... -0.228315  0.462622 -1.026213 -0.336315
3    -0.446080 -0.229863  ... -0.235701  0.463565 -1.028108 -0.342915
4    -0.471680 -0.207969  ... -0.232332  0.470300 -1.027213 -0.336200
...        ...       ...  ...       ...       ...       ...       ...
5132 -0.270507 -0.422914  ... -0.426504  0.664135 -0.776899 -0.688243
5133 -0.255784 -0.491147  ... -0.467682  0.632933 -0.759914 -0.762865
5134 -0.265482 -0.474894  ... -0.445592  0.639277 -0.754738 -0.736498
5135 -0.247722 -0.485608  ... -0.464260  0.632391 -0.754659 -0.763274
5136 -0.269328 -0.435432  ... -0.438046  0.612223 -0.778873 -0.714666

           x19       y19       z19       x20       y20       z20
0     0.558662 -1.225881 -0.365733  0.645383 -1.403194 -0.402040
1     0.566930 -1.229470 -0.366355  0.654401 -1.404609 -0.402018
2     0.572203 -1.204509 -0.392325  0.665830 -1.370468 -0.428388
3     0.573408 -1.212266 -0.397284  0.666025 -1.383456 -0.432468
4     0.582949 -1.208742 -0.390714  0.677675 -1.378430 -0.427127
...        ...       ...       ...       ...       ...       ...
5132  0.585261 -0.606164 -0.748247  0.436999 -0.436162 -0.751138
5133  0.540373 -0.563515 -0.837000  0.392246 -0.381208 -0.848915
5134  0.547630 -0.559971 -0.817339  0.389808 -0.382905 -0.834934
5135  0.533942 -0.552206 -0.845630  0.376543 -0.364129 -0.864099
5136  0.509849 -0.585398 -0.779045  0.356173 -0.407283 -0.784970

[5137 rows x 64 columns]>